import math

graph_config = {
    'graph1' : {
        'axis-len' : 2,
        'title' : 'x-axis position & current value',
	'x_label' : 'Time[s]',
	'y1_label' : 'position[mm]',
	'y2_label' : 'current value[%]',
	'fontsize' : 14,
	'x_index' : 'eTime',
	'y1_index' : ['D16'],
	'y2_index' : ['D22'],
	'y1_legend' : ['pos'],
	'y2_legend' : ['cur'],
	'y1_plot_color' : ['blue'],
	'y2_plot_color' : ['orange'],
	'x_lim_min' : 0,
	'x_lim_max' : lambda x : math.ceil(max(x)),
	'y1_lim_min' : -1600,
	'y1_lim_max' : 0,
	'y2_lim_min' : -100,
	'y2_lim_max' : 100,
    },
    'graph2' : {
        'axis-len' : 2,
        'title' : 'y-axis position & current value',
	'x_label' : 'Time[s]',
	'y1_label' : 'position[mm]',
	'y2_label' : 'current value[%]',
	'fontsize' : 14,
	'x_index' : 'eTime',
	'y1_index' : ['D66'],
	'y2_index' : ['D72'],
	'y1_legend' : ['pos'],
	'y2_legend' : ['cur'],
	'y1_plot_color' : ['blue'],
	'y2_plot_color' : ['orange'],
	'x_lim_min' : 0,
	'x_lim_max' : lambda x : math.ceil(max(x)),
	'y1_lim_min' : -600,
	'y1_lim_max' : 100,
	'y2_lim_min' : -100,
	'y2_lim_max' : 100,
    },
    'graph3' : {
        'axis-len' : 2,
        'title' : 'z-axis position & current value',
	'x_label' : 'Time[s]',
	'y1_label' : 'position[mm]',
	'y2_label' : 'current value[%]',
	'fontsize' : 14,
	'x_index' : 'eTime',
	'y1_index' : ['D116'],
	'y2_index' : ['D122'],
	'y1_legend' : ['pos'],
	'y2_legend' : ['cur'],
	'y1_plot_color' : ['blue'],
	'y2_plot_color' : ['orange'],
	'x_lim_min' : 0,
	'x_lim_max' : lambda x : math.ceil(max(x)),
	'y1_lim_min' : -600,
	'y1_lim_max' : 100,
	'y2_lim_min' : -100,
	'y2_lim_max' : 100,
    },
    'graph4' : {
        'axis-len' : 2,
        'title' : 'theta1-axis position & current value',
	'x_label' : 'Time[s]',
	'y1_label' : 'position[degree]',
	'y2_label' : 'current value[%]',
	'fontsize' : 14,
	'x_index' : 'eTime',
	'y1_index' : ['D166'],
	'y2_index' : ['D172'],
	'y1_legend' : ['pos'],
	'y2_legend' : ['cur'],
	'y1_plot_color' : ['blue'],
	'y2_plot_color' : ['orange'],
	'x_lim_min' : 0,
	'x_lim_max' : lambda x : math.ceil(max(x)),
	'y1_lim_min' : -50,
	'y1_lim_max' : 400,
	'y2_lim_min' : -100,
	'y2_lim_max' : 100,
    },
    'graph5' : {
        'axis-len' : 2,
        'title' : 'theta2-axis position & current value',
	'x_label' : 'Time[s]',
	'y1_label' : 'position[degree]',
	'y2_label' : 'current value[%]',
	'fontsize' : 14,
	'x_index' : 'eTime',
	'y1_index' : ['D216'],
	'y2_index' : ['D222'],
	'y1_legend' : ['pos'],
	'y2_legend' : ['cur'],
	'y1_plot_color' : ['blue'],
	'y2_plot_color' : ['orange'],
	'x_lim_min' : 0,
	'x_lim_max' : lambda x : math.ceil(max(x)),
	'y1_lim_min' : 0,
	'y1_lim_max' : 180,
	'y2_lim_min' : -100,
	'y2_lim_max' : 100,
    },
    'graph6' : {
        'axis-len' : 2,
        'title' : 'x2-axis position & current value',
	'x_label' : 'Time[s]',
	'y1_label' : 'position[mm]',
	'y2_label' : 'current value[%]',
	'fontsize' : 14,
	'x_index' : 'eTime',
	'y1_index' : ['D266'],
	'y2_index' : ['D272'],
	'y1_legend' : ['pos'],
	'y2_legend' : ['cur'],
	'y1_plot_color' : ['blue'],
	'y2_plot_color' : ['orange'],
	'x_lim_min' : 0,
	'x_lim_max' : lambda x : math.ceil(max(x)),
	'y1_lim_min' : -1200,
	'y1_lim_max' : 0,
	'y2_lim_min' : -100,
	'y2_lim_max' : 100,
    },
    'graph7' : {
        'axis-len' : 2,
        'title' : 'phi1-axis position & current value',
	'x_label' : 'Time[s]',
	'y1_label' : 'position[degree]',
	'y2_label' : 'current value[%]',
	'fontsize' : 14,
	'x_index' : 'eTime',
	'y1_index' : ['D316'],
	'y2_index' : ['D322'],
	'y1_legend' : ['pos'],
	'y2_legend' : ['cur'],
	'y1_plot_color' : ['blue'],
	'y2_plot_color' : ['orange'],
	'x_lim_min' : 0,
	'x_lim_max' : lambda x : math.ceil(max(x)),
	'y1_lim_min' : 80,
	'y1_lim_max' : 200,
	'y2_lim_min' : -100,
	'y2_lim_max' : 100,
    },
    'graph8' : {
        'axis-len' : 1,
        'title' : 'pad pressure',
	'x_label' : 'Time[s]',
	'y1_label' : 'pressure[kPa]',
	'fontsize' : 14,
	'x_index' : 'eTime',
	'y1_index' : ['D722', 'D724', 'D726'],
	'y1_legend' : ['p1-pre', 'p2-pre', 'p3-pre'],
	'y1_plot_color' : ['orange', 'fuchsia', 'darkorchid'],
	'x_lim_min' : 0,
	'x_lim_max' : lambda x : math.ceil(max(x)),
	'y1_lim_min' : -10,
	'y1_lim_max' : 100,
    },
}
